import type { Metadata } from "next";
import "./globals.css";

import { Provider } from "@/components/ui/provider";
import Header from "@/components/Header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <main>
                    <Provider>
                        <section>
                            <Header />
                        </section>
                        <section>{children}</section>
                    </Provider>
                </main>
            </body>
        </html>
    );
}
